### PR TITLE
Introduce a changelog

### PR DESCRIPTION
**Pull request by jaredbeck**
Per discussion in https://github.com/redis-store/redis-rails/issues/48

### CODE REVIEW

**Comment by tubbo** [comment]
I'm dropping support for Ruby v1.9 going forward in #52, so when that is merged please rebase this branch against 'master' (or you could update the message with "[ci skip]" and force-push...)

**Comment by jaredbeck** [comment]
> or you could update the message with "[ci skip]" and force-push...

Done.

**Comment by tubbo** [comment]
@jaredbeck you needed to wait until it was merged...please rebase again.

**Comment by tubbo** [comment]
@jaredbeck thanks for this!

**Pull request merged**
