### PR TITLE
Allow rails 6, bump ruby versions

### PR DESCRIPTION
**Pull request by trevorrjohn**

### CODE REVIEW

**Comment by tubbo** [comment]
@trevorrjohn our major versions don't (always) coincide with Rails', and `redis-activesupport` / `redis-actionpack` were recently released with new minor versions, so I'm pretty sure this is not necessary. did you have a problem with `gem 'redis-rails'` in Gemfile?

**Comment by trevorrjohn** [comment]
yeah I just realized I need to test this. I am currently using it with `rc2` and haven't had any issues. I just bumped ruby as I noticed it was a bit dated, but doesn't even look like travis is setup.

**Comment by trevorrjohn** [comment]
also i just realized what you meant about `redis-activesupport`, PR on the way.

**Comment by trevorrjohn** [comment]
and yes I had issues updating,

```
    redis-rails was resolved to 5.0.2, which depends on
      redis-activesupport (>= 5.0, < 6) was resolved to 5.0.7, which depends on
        activesupport (>= 3, < 6)
```

**Comment by tubbo** [comment]
@trevorrjohn sorry about that, turns out my redis-activesupport push never actually happened yesterday. I just ensured that it was on RubyGems, try a `bundle update redis-activesupport`

**Comment by trevorrjohn** [comment]
got it, ok all good now

**Pull request closed without merging**
