### PR TITLE
Rails 5 Support

### PR DESCRIPTION
**Pull request by schuylr**
Addresses #30 but requires updates to

* redis-rack
* redis-activesupport
* redis-actionpack

in order to work properly.

Tests will likely fail until then.

### CODE REVIEW

**Comment by pelcasandra** [comment]
+1

**Comment by ichord** [comment]
+1

**Comment by leifg** [comment]
+1

**Comment by tubbo** [comment]
These gem versions seem to be legit. I'm gonna merge this and see what happens. Shouldn't really affect anyone since the 4.x versions are still allowed.

**Comment by schuylr** [comment]
Thanks @tubbo :)

**Comment by greysteil** [comment]
Would be awesome to get a patch release for this now Rails 5.0.0.rc1 is out.

**Pull request merged**
