### PR TITLE
Test with all supported Rails versions #53

### PR DESCRIPTION
**Pull request by n-rodriguez**
Hi there!

I've updated CI config to be in line with https://github.com/redis-store/redis-actionpack and to add support for Rails 8 but while doing this I realized that this gem depends on https://github.com/redis-store/redis-activesupport which is now archived.

I think this gem can also be archived since it's blocked by https://github.com/redis-store/redis-activesupport/blob/master/redis-activesupport.gemspec#L22.

Thank you!

### CODE REVIEW

**Comment by n-rodriguez** [comment]
ping @tubbo

**Comment by tubbo** [comment]
my bad for the holdup guys merging this now

**Review by tubbo — APPROVED** [review]

**Comment by n-rodriguez** [comment]
No worries, thank you! 👍

**Comment by mpvosseller** [comment]
Any idea when this might get released? Thank you so much for the work on this.

**Pull request merged**
