### PR TITLE
Show server config settings for session_store

### PR DESCRIPTION
**Pull request by aceofspades**
While shown for cache_store, these were previously left out for the session_store

### CODE REVIEW

**Comment by tubbo** [comment]
Test failures seem related to #11, and that fix should also fix these test failures. Once #11 is merged into master, please rebase this branch.

**Comment by rthbound** [comment]
pinging @aceofspades ... #11 is merged. Can you rebase against master and push -f (for the conflicts)?

**Comment by aceofspades** [comment]
It's been a while, I'm not sure this is still relevant, do you know?

**Comment by rthbound** [comment]
@aceofspades since you mention it, it does look a little out of date. The commit in this PR is addressing a lack of documentation in the README that I don't believe exists in the current version of the README. Would you like to go on and close?

**Pull request closed without merging**
